name: Spell Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Run cSpell
        uses: streetsidesoftware/cspell-action@76c6f6d52abd57f4bcab5f3fde1bbd4f19a99eb0
        with:
          incremental_files_only: false
          files:  "**/*.{md,yaml,yml}"
          config: '.github/workflows/cspell.json'
